name: Release

on:
  # Run on push events on primary branches
  push:
    branches:
      - main
    tags:
      - 'v*'

  # Run on manual triggers
  workflow_dispatch:

# Set GITHUB_TOKEN permissions for the workflow
permissions:
  contents: read

# Allow one concurrent deployment
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:

  # Build job
  build:
    name: Build Astro site artifact
    runs-on: ubuntu-latest
    timeout-minutes: 10

    # Set outputs
    outputs:
      version: ${{ env.VERSION }}

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Set version tag for pre-release
      if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
      # Use datetime and short commit hash as the pre-release tag name
      env:
        GITHUB_SHA: ${{ github.sha }}
      run: echo "VERSION=t$(date +%Y%m%d.%H%M%S).${GITHUB_SHA::4}" >> $GITHUB_ENV

    - name: Set version tag for release
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      # Use the tag name as the release tag name, without the git ref prefix
      # Ensure the tag name starts with 'v'
      env:
        GITHUB_REF: ${{ github.ref }}
      run: |
        VERSION=${GITHUB_REF##refs/tags/}
        VERSION=${VERSION##v}
        echo "VERSION=v$VERSION" >> $GITHUB_ENV

    - name: Set VERSION file
      env:
        VERSION: ${{ env.VERSION }}
      run: echo $VERSION > ./app/app/VERSION.txt

    - name: Build for production
      run: docker compose -f docker-compose.yml -f docker-compose.cicd.yml build

    - name: Copy application files
      run: docker compose -f docker-compose.yml -f docker-compose.cicd.yml run --rm app

    - name: Upload dist folder
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: ./app/dist
        if-no-files-found: error

  # Release job
  release:
    name: Release version
    runs-on: ubuntu-latest
    timeout-minutes: 5

    # Dependencies
    needs:
      - build

    # Set GITHUB_TOKEN permissions for this job
    permissions:
      contents: write

    # Set deployment environment
    environment:
      name: release
      url: ${{ steps.release.outputs.url }}

    steps:

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: dist
        path: ./dist

    - name: Infer if the version is a pre-release
      # PEP 440 specifies that pre-releases have suffixes, such as:
      # `1.0.0.a1`, `1.0.0b2`, `1.0.0rc1`, `1.0.0.dev1`, `1.0.0.post1`
      # Consider a version is a pre-release if it has any non-numeric characters
      # Ignore the first character
      env:
        VERSION: ${{ needs.build.outputs.version }}
      run: |
        VERSION=${VERSION:1}
        if ( echo $VERSION | grep -q '[^0-9]' ); then
          echo "PRE_RELEASE=true" >> $GITHUB_ENV
        else
          echo "PRE_RELEASE=false" >> $GITHUB_ENV
        fi

    - name: Create release
      id: release
      uses: softprops/action-gh-release@v1
      with:
        # Use the version tag
        tag_name: ${{ needs.build.outputs.version }}
        # Set the release as non-prerelease if not triggered on a tag
        prerelease: ${{ env.PRE_RELEASE == 'true' }}
        target_commitish: ${{ github.sha }}
        files: ./dist/*
        fail_on_unmatched_files: true
        generate_release_notes: true
